version: "3"

tasks:
  backend:
    desc: Run FastAPI backend with uv + uvicorn (reload)
    cmds:
      - uv run uvicorn celine.assistant.main:app --host 0.0.0.0 --port 8012 --reload
    env:
      PYTHONUNBUFFERED: "1"
